__all__ = ['CHANNEL_EVENT_PREFIX_BYTES', 'CHANNEL_EVENT_PREFIX', 'NEWLINE_BYTES']

CHANNEL_EVENT_PREFIX = "moss_channel_event:"
CHANNEL_EVENT_PREFIX_BYTES = CHANNEL_EVENT_PREFIX.encode('utf-8')
NEWLINE_BYTES = b'\n'
