__all__ = [
    'POSITION_ARGS_KEY', 'SCOPE_SHORTCUT', 'SCOPE_CHANNEL_NAME_KEY', 'CALL_ID_RESERVE_KEY', 'SCOPE_COMMAND_NAME'
]

POSITION_ARGS_KEY = "_args"
SCOPE_SHORTCUT = '_'
SCOPE_COMMAND_NAME = '__scope__'
CONTENT_COMMAND_NAME = '__content__'
CALL_ID_RESERVE_KEY = '_id'
SCOPE_CHANNEL_NAME_KEY = 'name'
